#!/usr/bin/env bash

################################################################################
# Template for quickly getting started when facing the task of writing smaller
# bash scripts. To suggest a good structure, and serve as a reminder for some of
# the details and conventions of bash.
#
# jseb@github 2011-10-29
#
################################################################################

# -- useful bash modes ---------------------------------------------------------
# set -o xtrace
# After  expanding  each simple command, for command, case command, select
# command, or arithmetic for command, display the expanded value of PS4,
# followed by the command and its expanded arguments or associated word list.
# (in plain english: print everything that gets executed, great for debugging)

set -o errexit
# Exit immediately if a simple command (see SHELL GRAMMAR) exits with a
# non-zero status.

set -o nounset
# Treat unset variables as an error when performing parameter expansion.  If
# expansion is attempted on an unset variable, the shell prints an error
# message, and, if not interactive, exits with a non-zero status.

# -- global variables ----------------------------------------------------------
tmpdir="/tmp/$RANDOM-$RANDOM-$RANDOM"
feed_path="$tmpdir/feed.xml"
number_of_episodes=20

# -- functions -----------------------------------------------------------------
function print_start() {
    bold="\033[1m"
    normal="\033[0m"
    abgt="Group Therapy with Above & Beyond"
    link="aboveandbeyond.nu"
    echo -e "$bold$abgt"
    line=$(sed 's/./-/g' <<< $abgt)
    index=$(((${#abgt}-${#link})/2))
    echo -e $normal${line:0:index-1} $link ${line:0:index-1}"\n"
}

function download_feed() {
    $(curl -f -s -o "$feed_path" "http://static.aboveandbeyond.nu/grouptherapy/podcast.xml" || true)
}

function play() {
    echo -e "Playing the $number_of_episodes latest episodes.\nPress 'h' for controls."
    mpg123 -qC $1
}

function play_latest_episodes() {
    episode_urls=$(tail -r "$1" | grep enclosure | grep -o "http://[a-zA-Z0-9.\/_]*.mp3" | head -n $number_of_episodes || true)
    episode_urls=$(sed 's/\n/ /g' <<< $episode_urls)
    if [ -n "$episode_urls" ]
    then
        play "$episode_urls"
    else
        echo "Error: No episodes found."
    fi
}

function cleanup() {
    # remove temporary work dir
    if [[ -d "$tmpdir" ]]
    then
        # cd into /tmp first, just in case $tmpdir has been set to any path
        # outside of /tmp. Also, chaining the commands so that if cd /tmp
        # fails, rm -rf will not get executed
        cd /tmp && rm -rf $(basename "$tmpdir")
    fi
}

# -- initialize ----------------------------------------------------------------
# -- error handling
# this trap is run on any exit, signalled or not
trap cleanup EXIT

hash mpg123 2>&- || ( echo >&2 "ERROR: mpg123 not installed, exiting.." && exit 1 )
hash curl 2>&- || ( echo >&2 "ERROR: curl not installed, exiting.." && exit 1 )

# -- temporary work dir
mkdir "$tmpdir" && cd "$tmpdir"

# -- main ----------------------------------------------------------------------
print_start
download_feed
if [ -e "$feed_path" ]  && [ -s "$feed_path" ]
then
    play_latest_episodes "$feed_path"
else
    echo "ERROR: Failed to get feed."
fi
